project:
  type: website

website:
  title: "Carlos Llosa"
  description: "Personal website of Carlos Llosa"
  site-url: https://carlosllosa.com
  repo-url: https://github.com/carlosllosa/website
  google-analytics: "G-39ERQKY9NZ"
  twitter-card: true
  open-graph:
    locale: en_US
  favicon: favicon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - papers.qmd
      - software.qmd
      - resume.qmd
      - icon: linkedin
        url: "https://www.linkedin.com/in/carlos-llosa-83a77aa2"
      - icon: github
        url: "https://github.com/carlos-llosa/"
  page-footer:
    left: "© Copyright 2025 Carlos Llosa. Except where otherwise noted"
  cookie-consent: true

execute:
  freeze: auto

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
